### ISSUE TITLE
overflow leads to panic at runtime

### ISSUE THREAD

**Issue by wez** [nical/guillotiere#25]
This program:

```rust
use guillotiere::{AtlasAllocator, Size };
fn main() {
    let mut allocator = AtlasAllocator::new(Size::new(65536, 65536));
    println!("{:?}", allocator.allocate(Size::new(19,34)));
}
```

produces:

```
thread 'main' panicked at 'attempt to multiply with overflow', /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/arith.rs:341:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:50:5
   3: <i32 as core::ops::arith::Mul>::mul
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/arith.rs:334:45
   4: euclid::size::Size2D<T,U>::area
             at /Users/wez/.cargo/registry/src/github.com-1ecc6299db9ec823/euclid-0.22.6/src/size.rs:277:9
   5: guillotiere::allocator::AtlasAllocator::allocate
             at /Users/wez/.cargo/registry/src/github.com-1ecc6299db9ec823/guillotiere-0.6.1/src/allocator.rs:537:16
   6: g::main
             at ./src/main.rs:4:22
   7: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
```

when built in release mode:

```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 4294967295', /Users/wez/.cargo/registry/src/github.com-1ecc6299db9ec823/guillotiere-0.6.1/src/allocator.rs:562:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:69:5
   3: guillotiere::allocator::AtlasAllocator::allocate
   4: g::main
```

**Comment by nical** [comment]
Hi, thanks for filing this. I have a fix on the way but your workaround of using the simple allocator since you don't need deallocations is a good thing because it should give you the same result with much better performance.
